### ISSUE TITLE
Legend or labeling for small outcomes

### ISSUE THREAD

**Issue by emhart** [mbojan/alluvial#37]
I'm looking to find a way to easily label small slices of an alluvial diagram. Right now my label is too big for the small piece in the upper right corner.  Ideally I was thinking a legend or something like that.  

![alluvial_1](https://cloud.githubusercontent.com/assets/1039395/25405042/c7345964-29b6-11e7-8a7b-747ebb6b5960.png)

**Comment by mbojan** [comment]
A reprex:

``` r
library(alluvial)
d <- expand.grid(
  x=1,
  y=1:3
)
d$n <- rep(1, 3)
d$n <- with(d, ifelse(y %in% c(1,3), 0.01, n))
alluvial(d[,-3], freq=d$n, alpha=1, border="black")
```

![](http://i.imgur.com/mdXfMmQ.png)

Approaches that come to mind include:

- Try plotting with a different aspect ratio, e.g. make height twice the width
- Make a space to the right of the plot and put category labels there (a bit like `alluvial_ts` example in the README

I'll cook-up some examples tomorrow (CET).

**Comment by mbojan** [comment]
I have improved the data returned by `alluvial` which facilitates adding further elements. You will need to install the dev version of the package from GitHub.

To address your issue @emhart you can add more space to the right of the plot and put labels there. For example using the data frame above:

```r
x <- alluvial(d[,-3], freq=d$n, ann=FALSE, mar=c(2,1,1,5))
text(1, x$category_midpoints$x, names(x$category_midpoints$x))
op <- par(xpd=NA)
text(2.15, x$category_midpoints$y, names(x$category_midpoints$y))
par(op)
```

- Setting `ann` to FALSE suppresses label printing
- Adjusting default `mar` to make right margin larger (5 not default 1)
- First `text()` adds labels to the first axis
- Second `text()` places label on the right margin
- It is necessary to temorarily set `xpd` to `NA` so that the labels are not clipped

Does that work for you?
